### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Jason's Curriculum Vitae
# description: This will be meta HTML tag content. This can be ignored.
description: this is my curriculum vitae.
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Jason
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: this is my curriculum vitae.
# email: Your E-Mail address for the email button.
email: eatonj@umich.edu
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: retroprose
#codepen_username: exampleUser
#dev_username: exampleUser
linkedin_username: jason-eaton-07002455
twitter_username: retroprose

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: <p>I believe that one of the most important tasks in a society is making sure education is passed down in such a way that goes beyond indoctrination and empowers the next generation to explore new horizons without dismantling the benefits of tradition.  I have had several interests as my career has progressed, but my primary interest is research and experimentation.  This interest began when I was young, as I had an AppleIIe to play with when I was only two years old.  I had a strong interest in video games growing up, and started studying computer science and video game architecture in high school before there were any official classes to teach them.  I was part of the first group of kids to get to be in a computer science class that was started by our geometry teacher.  I continued to study video game architecture through college, but lost interest in video games in general after having the opportunity to study various world religions in college.</p><p>I decided to acquire a master’s so that I could teach college level courses, and switched my studies from low level coding used in video game development to web application development.  I have worked several years doing web development, but prefer the coding that I used to do when I was younger.  I hoped to start teaching computer science, but there was a lack of openings at schools with real computer science programs.  Fortunately, web coding has started to go back to more low level languages to allow web applications to scale to large numbers of users, which has made my previous skills relevant again.  At the University of Michigan we had to take many courses on how to write low level software from scratch, I hope to teach in this way in the future as schools tend to have students learn countless frameworks without learning the foundations of computer science.</p><p>Many of my jobs were acquired through my original video game development experience, but would rather apply these skills to something less entertainment related.  I considered getting a PhD that would allow me to do some research on education gaming in the field of economics.  Unfortunately most of the colleges in the United States are liberal colleges, and these institutions tend to indoctrinate students rather than help them really understand what is happening behind the scenes.  I have studied many alternate theories of economics and believe interactive simulations would be key for students to get beyond indoctrination and develop a stronger intuition that would allow them to see how economics is manipulated by questionable personalities in the modern world.</p><p>One positive aspect of a liberal college though is exposure to other cultures.  At the University of Michigan I have worked with nearly every ethnic background.  After college I spent time traveling to many indian temples, and also met people practicing the same faith as me from many backgrounds.  One culture I am particularly fond of is Russian culture.  I worked with several Russians when I was doing political action near the end of my college days, and also when traveling to many temples.  I met a Russian monk a few years ago that taught me about the country, and sparked my interest in visiting long term some day.  This past year I finally took the plunge and started studying the Russian language and have been enjoying every minute of it.  I didn’t have a lot of interest in studying languages until recently, although I have been exposed to Sanskrit for many years.  I even started making plans to visit this summer and take a several month long Russian language course, but unfortunately due to Covid I cannot get a visa to get into the country.</p>

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

show_activity_card: true
activity_title: Activities

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://example.com/

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Awards

show_presentations: true
presentations_title: Presentations

show_jobs: true
jobs_title: Work Experience

show_education: true
education_title: Education

# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: false
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: 2461 Hoover Ave<br />West Bloomfield, MI 48324<br />eatonj(at)umich.edu<br />2four8.9three3.1fourfive9<br /><a class="highlight-link" href="/assets/files/resume.pdf" target="_blank" rel="noreferrer">Resume Link</a>

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: eatjason/eatjason.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
